apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: clusters/addons/lab-control/argocd
    repoURL: https://github.com/dgmorales/argocd-lab.git
    targetRevision: HEAD