apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testapp
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: git@github.com:dgmorales/argocd-lab.git
          revision: HEAD
          files:
          - path: config/testapp-clusters.yaml
      - list:
          elementsYaml: "{{ .clusters | toJson }}"
  template:
    metadata:
      name: '{{.name}}-testapp'
      finalizers:
        # cascade delete app resources
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL:  https://github.com/dgmorales/argocd-lab.git
        targetRevision: {{.repoRef}}
        path: manifests/{{.name}}
      destination:
        name: '{{.name}}'
        namespace: testapp
      syncPolicy:
        syncOptions:
        - CreateNamespace=true