apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testapp
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          # only add app to worker clusters
          role: worker
  template:
    metadata:
      name: '{{.name}}-testapp'
      finalizers:
        # cascade delete app resources
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL:  https://github.com/dgmorales/argocd-lab.git
        targetRevision: HEAD
        path: manifests/
      destination:
        name: '{{.name}}'
        namespace: testapp
      syncPolicy:
        syncOptions:
        - CreateNamespace=true