name: Deploy testapp

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" tag
  push:
    branches: [ "test-argo-workflow" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dev:
    name: Dev Deploy to lab-worker-0
    runs-on: self-hosted
    environment:
      name: dev
      url: https://github.com
    steps:
      - name: test step
        run: |
          echo "This is a test step"
  prod:
    name: Prod Deploy to lab-worker-1
    runs-on: ubuntu-latest
    needs: dev
    environment:
      name: prod
      url: https://github.com
    steps:
      - name: test step
        run: |
          echo "This is a test step"