name: Deploy testapp

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" tag
  push:
    branches: [ "test-argo-workflow" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dev:
    name: Dev Deploy to lab-worker-0
    runs-on: self-hosted
    environment:
      name: dev
      url: https://github.com
    env:
      ARGOCD_SERVER: ${{ vars.ARGOCD_SERVER }}
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
    steps:
      - name: Sync testapp
        run: |
          wget -O /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.14.6/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
          ls -l /usr/local/bin/argocd
          env
          argocd app sync lab-worker-0-testapp
          argocd app wait lab-worker-0-testapp
  prod:
    name: Prod Deploy to lab-worker-1
    runs-on: ubuntu-latest
    needs: dev
    environment:
      name: prod
      url: https://github.com
    env:
      ARGOCD_SERVER: ${{ vars.ARGOCD_SERVER }}
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
    steps:
      - name: Sync testapp
        run: |
          wget -O /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.14.6/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
          argocd app sync lab-worker-1-testapp
          argocd app wait lab-worker-1-testapp